language: c
compiler:
  - gcc
  - clang

branches:
  only:
    - master

script:
  - make clean
  - make install

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - camarllon@gmail.com
